export const CLIENT_CSS = `
.dsh-lark-settings{max-width:880px;padding:8px 2px 36px;color:var(--text-primary,#16181d)}
.dsh-lark-header{display:flex;align-items:flex-start;justify-content:space-between;gap:20px;margin-bottom:20px}.dsh-lark-header h2{margin:0;font-size:22px}.dsh-lark-header p{margin:6px 0 0;color:var(--text-secondary,#586174)}
.dsh-lark-runtime{display:flex;align-items:center;gap:8px;border:1px solid var(--border-subtle,#dfe3ea);border-radius:999px;padding:7px 12px;font-size:13px;font-weight:600;white-space:nowrap}
.dsh-lark-card{display:grid;gap:16px;margin:0 0 14px;padding:20px;border:1px solid var(--border-subtle,#dfe3ea);border-radius:12px;background:var(--surface-primary,#fff)}.dsh-lark-card h3{margin:0;font-size:15px}
.dsh-lark-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:14px}.dsh-lark-card label{display:grid;gap:7px;font-size:13px;font-weight:600}.dsh-lark-card select,.dsh-lark-card textarea{box-sizing:border-box;width:100%;border:1px solid var(--border-default,#cbd1dc);border-radius:8px;background:var(--surface-primary,#fff);color:inherit;font:inherit;padding:9px 11px}.dsh-lark-card textarea{min-height:82px;resize:vertical}.dsh-lark-card select:focus-visible,.dsh-lark-card textarea:focus-visible{outline:2px solid var(--accent-primary,#3b72e8);outline-offset:2px}
.dsh-lark-check{display:flex!important;align-items:center;gap:9px}.dsh-lark-check input{width:16px;height:16px}.dsh-lark-credential{display:flex;align-items:center;gap:9px;color:var(--text-secondary,#586174);font-size:12px}.dsh-lark-credential-badge{display:inline-flex;align-items:center;gap:7px;border:1px solid currentColor;border-radius:999px;padding:4px 9px;font-weight:700}.dsh-lark-credential[data-state=configured] .dsh-lark-credential-badge{color:var(--success-text,#137333);background:var(--success-surface,#e8f5e9)}.dsh-lark-credential[data-state=missing] .dsh-lark-credential-badge{color:var(--warning-text,#9a6700);background:var(--warning-surface,#fff4ce)}.dsh-lark-credential-dot{width:7px;height:7px;border-radius:50%;background:currentColor}.dsh-lark-credential code{padding:2px 6px;border-radius:5px;background:var(--surface-secondary,#f2f4f7)}
.dsh-lark-actions{display:flex;align-items:center;gap:10px;min-height:36px}.dsh-lark-actions [role=status]{font-size:13px;color:var(--text-secondary,#586174)}.dsh-lark-detail,.dsh-lark-loading{color:var(--text-secondary,#586174);font-size:13px}
@media(max-width:680px){.dsh-lark-header{align-items:stretch;flex-direction:column}.dsh-lark-runtime{align-self:flex-start}.dsh-lark-grid{grid-template-columns:1fr}.dsh-lark-actions{align-items:stretch;flex-direction:column}.dsh-lark-actions button{width:100%}}
@media(prefers-reduced-motion:reduce){.dsh-lark-settings *{scroll-behavior:auto!important;transition:none!important}}
`
